### ISSUE TITLE
error in etf_db setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "', pandas'": Expected stringEnd

### ISSUE THREAD

**Issue by constructor-s** [lauraporta/etf-db#2]
There is a typo in the line below missing the leading `(` and the `'`s

https://github.com/lauraporta/etf-db/blob/3f09f74cb8eeb4f52f39771ff0870a9554b47867/setup.py#L9

**Comment by constructor-s** [comment]
The file should read:

```python
from setuptools import setup

setup(name = 'etf_db',
    version = '0.0.1',
    description = 'A python package for downloading public data from etfdb.com screener tool',
    author = 'Laura Porta',
    author_email = 'porta.laura.2@gmail.com',
    packages = ['etf_db'],
    install_requires = ('requests', 'pandas')
    )
```

**Comment by lauraporta** [comment]
Thank you, I fixed it! Let me know if you encounter other bugs.

**Comment by constructor-s** [comment]
`'json' 'logging', 'datetime'` are built-in libraries for all Python versions so you do not need to include them in `setup.py` or `requirements.txt`

https://github.com/lauraporta/etf-db/blob/cc35c64f15cc0d756b8f7297bbd878cab4d1836c/requirements.txt#L3-L6

https://github.com/lauraporta/etf-db/blob/cc35c64f15cc0d756b8f7297bbd878cab4d1836c/setup.py#L9
