### ISSUE TITLE
AttributeError: module 'datetime' has no attribute 'now'

### ISSUE THREAD

**Issue by constructor-s** [lauraporta/etf-db#4]
This line as it is raises `AttributeError: module 'datetime' has no attribute 'now'`

https://github.com/lauraporta/etf-db/blob/b81ab8362e55ff04e551d7306d1cd3425dd4b243/etf_db/utils.py#L6-L9

Either you meant `datetime.datetime.now()` on line 9 or you meant to import as: `from datetime import datetime` on line 6.

See https://docs.python.org/3/library/datetime.html#datetime.datetime.now, the first `datetime` is the library name, the second `datetime` is the `datetime` class, and `now()` is a classmethod of the `datetime` class

**Comment by lauraporta** [comment]
Thank you for your contribution! It should be fixed now.
